logging:
  level:
    cn:
      licoy:
        wdog: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring:
  datasource:
    url: jdbc:mysql://122.51.67.240:9036/biz_nbee?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: Ds&8&qrzZXxQuJImB&95
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  redis:
    host: 122.51.67.240
    port: 6399
    password: yushangcc
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
    auto: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  #给项目来个名字
  application:
    name: appotmq
  #配置rabbitMq 服务器
  rabbitmq:
    host: 122.51.67.240
    port: 5682
    username: admin
    password: appot2020
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 100MB
      #      最大支持请求大小
      max-request-size: 100MB

#filepath: C:/mc/works/biz_nbee/xls/
filepath: /home/biz_new_bee/webapps/xls/

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 81
  maxHttpHeaderSize: 10240000
  maxHttpPostSize: 10240000
  tomcat:
    max-threads: 1000
    min-spare-threads: 300
    maxHttpHeaderSize: 10240000
    maxHttpPostSize: 10240000
resources: # 指定静态资源的路径
  static-locations: classpath:/static/,classpath:/views/,classpath:/staticc/,classpath:/yushangweb/
  cache-period: 0

